import os

COLDBREW_IS_PROD = os.environ.get('COLDBREW_IS_PROD', "false") == "true"
COLDBREW_SCALE_MAC_ADDRESS = os.environ['COLDBREW_SCALE_MAC_ADDRESS']
COLDBREW_INFLUXDB_TOKEN = os.environ['COLDBREW_INFLUXDB_TOKEN']
COLDBREW_INFLUXDB_URL = os.environ['COLDBREW_INFLUXDB_URL']
COLDBREW_INFLUXDB_ORG = os.environ['COLDBREW_INFLUXDB_ORG']

_bucket =
COLDBREW_INFLUXDB_BUCKET = os.getenv('COLDBREW_INFLUXDB_BUCKET', 'coldbrew') if COLDBREW_IS_PROD else')
