import os

COLDBREW_IS_PROD = os.environ.get('COLDBREW_IS_PROD', "false") == "true"
print(f"COLDBREW_IS_PROD = {COLDBREW_IS_PROD}")
COLDBREW_SCALE_MAC_ADDRESS = os.environ['COLDBREW_SCALE_MAC_ADDRESS'] if COLDBREW_IS_PROD else ""
COLDBREW_INFLUXDB_URL = os.environ['COLDBREW_INFLUXDB_URL']
print(f"COLDBREW_INFLUXDB_URL = {COLDBREW_INFLUXDB_URL}")
COLDBREW_INFLUXDB_TOKEN = os.environ['COLDBREW_INFLUXDB_TOKEN']
COLDBREW_INFLUXDB_ORG = os.environ['COLDBREW_INFLUXDB_ORG']

# if this is ever changed, need to also change grafana dashboard queries
COLDBREW_INFLUXDB_BUCKET = os.getenv('COLDBREW_INFLUXDB_BUCKET', 'coldbrew') if COLDBREW_IS_PROD else os.getenv('COLDBREW_INFLUXDB_BUCKET', 'coldbrew') + '-dev'
print(f"COLDBREW_INFLUXDB_BUCKET = {COLDBREW_INFLUXDB_BUCKET}")